# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MissingPersons' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'ProjectOxfordFace'
  # Pods for MissingPersons
#pod 'ProjectOxfordFace'

pod ‘Firebase’
pod ‘Firebase/Storage’
pod 'Alamofire', '~> 3.4'

end
